version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=airflow
      - RABBITMQ_DEFAULT_VHOST=airflow

    ports: 
      # admin gui
      - 8020:15672
      # queue 
      - 8021:5672

  master:
    image: donaurelio/datacube:1.8.2-airflow-2.0.0
    restart: always
    command: bash /home/datacube/airflow/entrypoint.sh
    environment:
      - PATH=$PATH:/home/datacube/.local/bin
      - AIRFLOW_HOME=/home/datacube/airflow
      - C_FORCE_ROOT=true
    volumes:
      - ./airflow:/home/datacube/airflow
    ports:
      # airflow web server
      - 8080:8080
      # flower
      - 5555:5555
    depends_on:
      - postgres
      - rabbitmq

  worker:
    image: donaurelio/datacube:1.8.2-airflow-2.0.0
    restart: always
    command: bash -c "airflow celery worker"
    environment:
      - PATH=$PATH:/home/datacube/.local/bin
      - AIRFLOW_HOME=/home/datacube/airflow
      - C_FORCE_ROOT=true
    volumes:
      - ./airflow:/home/datacube/airflow
    depends_on:
      - postgres
      - rabbitmq
      - master
